source "https://rubygems.org"

ruby "3.4.1"

gem "rails", "~> 7.1.5", ">= 7.1.5.1"
gem "puma", ">= 5.0"
gem "bcrypt"
gem "jwt"
gem "rack-cors"
gem "active_model_serializers"
gem "pg"
gem "nokogiri", "~> 1.16.2"
gem "jbuilder"
gem "image_processing", "~> 1.2"
gem "bootsnap", require: false
gem "sidekiq"
gem "redis"
gem "sidekiq-cron"
gem "aws-sdk-s3", "~> 1.130"

group :development, :test do
  gem "debug", platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem "rspec-rails", "~> 7.1"
end

group :development do
  # gem "spring"
end

gem "tzinfo-data", platforms: %i[mswin mswin64 mingw x64_mingw jruby]