export const DISCUSSION_API_URL = import.meta.env.VITE_DISCUSSION_API_URL;
export const DISCUSSION_THREAD_POPULAR_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_POPULAR_API_URL;
export const DISCUSSION_THREAD_WEEK_POPULAR_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_POPULAR_API_URL;
export const DISCUSSION_THREAD_RECENT_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_RECENT_API_URL;
export const DISCUSSION_RECOMMEND_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_RECOMMEND_API_URL;
export const DISCUSSION_THREAD_ADMIN_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_ADMIN_API_URL;
export const DISCUSSION_THREAD_ADMIN_RECOMMENDED_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_ADMIN_RECOMMENDED_API_URL;
export const DISCUSSION_THREAD_ADMIN_POSTS_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_ADMIN_POSTS_API_URL;
export const POSTS_API_URL = import.meta.env.VITE_POSTS_API_URL;
export const LOGIN_API_URL = import.meta.env.VITE_LOGIN_API_URL;
export const LOGIN_ADMIN_USER_API_URL = import.meta.env.VITE_LOGIN_ADMIN_USER_API_URL;
export const POSTS_REPORT_API_URL = import.meta.env.VITE_POST_REPORT_API_URL;
export const ADMIN_POSTS_REPORT_API_URL = import.meta.env.VITE_ADMIN_POST_REPORT_API_URL;
export const REPORT_CONTENTS_API_URL = import.meta.env.VITE_REPORT_CONTENTS_API_URL;