export const DISCUSSION_API_URL = import.meta.env.VITE_DISCUSSION_API_URL;
export const DISCUSSION_THREAD_POPULAR_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_POPULAR_API_URL;
export const DISCUSSION_THREAD_WEEK_POPULAR_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_POPULAR_API_URL;
export const DISCUSSION_THREAD_RECENT_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_RECENT_API_URL;
export const DISCUSSION_RECOMMEND_API_URL = import.meta.env
  .VITE_DISCUSSION_THREAD_RECOMMEND_API_URL;
export const POSTS_API_URL = import.meta.env.VITE_POSTS_API_URL;
export const LOGIN_API_URL = import.meta.env.VITE_LOGIN_API_URL;
